show databases;
-- drop database resume_project;
create database resume_project;
use resume_project;
show tables;

create table dim_date(
Date_ date ,
month_	varchar(10),
quarter_ varchar(2)	,
fiscal_year_ year 
);

create table dim_districts(
dist_code varchar(10) ,
district varchar(30)
);

create table fact_stamps(
dist_code varchar(10),
month date,
documents_registered_cnt int,
documents_registered_rev int,
estamps_challans_cnt int,
estamps_challans_rev int
);

select * from dim_date;
select * from dim_districts;
select * from fact_stamps;
select * from fact_transport;
#imported using Table data import wizard
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------
#creating table having the district , documents_registered_rev and month(date of the registration) 
create table dist_rev as select dist.district , rev.documents_registered_rev, rev.month
from dim_districts as dist 
inner join fact_stamps as rev 
on dist.dist_code = rev.dist_code ;

#creating table with district and sum of total revenue generated by documents_registered revenue for each district in all yrs
create table dist_rev_all_years select district, sum(documents_registered_rev) as total_doc_reg_rev from dist_rev
group by district order by total_doc_reg_rev desc ;

#creating table having district's name, num. of docs registered, revenue from docs registered
create table dist_activities as select dist.district , rev.documents_registered_cnt as num_docs_reg, rev.documents_registered_rev
from dim_districts as dist inner join
fact_stamps as rev 
on dist.dist_code = rev.dist_code ;

#creating table having the same but grouped by district
create table dist_acts select district, sum(documents_registered_rev) as total_doc_reg_rev, sum(num_docs_reg) as num_of_doc_reg
from dist_activities group by district order by total_doc_reg_rev desc ;
select * from dist_acts;
-- ------------------------------------------------------------ TABLE 2 USED IN THE NOTEBOOK-----------------------------------------------------------
#creating table with district and sum of total revenue generated by documents_registered revenue for each district withing FY 2019-2022
create table dist_rev_main select district, sum(documents_registered_rev) as total_doc_reg_rev from dist_rev where 
month between '2019-10-01' and '2022-09-30' group by district order by total_doc_reg_rev desc ;

select * from dist_rev_main; #Exported using Export option from result grid
-- ------------------------------------------------------------ TABLE 1 USED IN THE NOTEBOOK-----------------------------------------------------------
show tables;
select * from fact_stamps;

#creating table having docs registration , estamps challan revenue of each district in all yrs
create table estamp_doc_rev 
select e.documents_registered_rev, e.estamps_challans_rev, d.district 
from fact_stamps as e
inner join dim_districts as d 
on e.dist_code = d.dist_code;

#creating table having total registration and estamps challan revenue grouped by each district in all yrs
create table dist_e_reg_rev select district, sum(documents_registered_rev) as total_doc_reg_rev, sum(estamps_challans_rev)
as estamp_challan_rev 
from estamp_doc_rev group by district order by  total_doc_reg_rev desc;

select * from dist_e_reg_rev;
-- ------------------------------------------------------------ TABLE 3 USED IN THE NOTEBOOK-----------------------------------------------------------

#creating table having docs registration , estamps challan revenue and its dates of each district in all yrs
create table estamp_rev_dates as
select e.month, e.estamps_challans_rev, d.district 
from fact_stamps as e
inner join dim_districts as d 
on e.dist_code = d.dist_code;

#creating table having estamps challan revenue grouped by each district in FY 2022
create table estamp_rev_req as select district, sum(estamps_challans_rev) as total_estamp_rev
from estamp_rev_dates where month between "2021-04-01" and "2022-03-31" 
group by district order by total_estamp_rev desc;

select * from estamp_rev_req;
-- ------------------------------------------------------------ TABLE 4 USED IN THE NOTEBOOK-----------------------------------------------------------
#creating tale including district name, its docs_registered_count and estamps_challan_count of all duration

create table estamp_doc_reg_cnt as select d.district, e.month as date,e.documents_registered_cnt, e.estamps_challans_cnt from fact_stamps as e 
inner join dim_districts as d  where d.dist_code = e.dist_code;

select * from estamp_doc_reg_cnt;
-- ------------------------------------------------------------ TABLE 5 USED IN THE NOTEBOOK-----------------------------------------------------------
create table estamp_rev_fy21 as  select d.district, e.estamps_challans_rev  from dim_districts
as d inner join fact_stamps as e where d.dist_code = e.dist_code and e.month between '2021-04-01' and '2022-03-31' ;

create table estamp_rev_req_fy21_22 as select district, sum(estamps_challans_rev) as estamps_challans_rev 
from estamp_rev_fy21 group by district order by sum(estamps_challans_rev);

select * from estamp_rev_req_fy21_22 ;
-- ------------------------------------------------------------ TABLE 5 USED IN THE NOTEBOOK-----------------------------------------------------------
create table fuel_season_corr as select  dim.Date_, dim.month_ ,dim.quarter_,ft.fuel_type_petrol, d.district
from fact_transport as ft join dim_districts as d on ft.dist_code=d.dist_code 
join dim_date as dim where  date(ft.month) =dim.Date_ ;

select * from fuel_season_corr ;
-- ------------------------------------------------------------ TABLE 6 USED IN THE NOTEBOOK-----------------------------------------------------------
create table dist_vehicals_distribution as select date(t.month) as date, d.district, t.vehicleClass_MotorCycle, t.vehicleClass_MotorCar,
 t.vehicleClass_AutoRickshaw,
t.vehicleClass_Agriculture from dim_districts as d join fact_transport as t where d.dist_code = t.dist_code and t.month between '2021-04-01' 
and '2022-03-31' ;

create table dist_grpd_veh_distr as select district, sum(vehicleClass_MotorCycle) as total_motorcycles , 
sum(vehicleClass_MotorCar) as total_motorcars,
 sum(vehicleClass_AutoRickshaw) as total_rickshaws, sum(vehicleClass_Agriculture) as total_agro_vehicles
from dist_vehicals_distribution group by district ;

select * from dist_grpd_veh_distr order by total_motorcycles desc;
-- ------------------------------------------------------------ TABLE 7 USED IN THE NOTEBOOK-----------------------------------------------------------
create table dist_veh_type_sales as select date(ft.month) as date, ft.fuel_type_diesel as Diesel_vehicles, 
ft.fuel_type_electric as Electric_vehicles, ft.fuel_type_petrol as Fuel_vehicles,
d.district from fact_transport as ft inner join dim_districts as d where ft.dist_code =  d.dist_code and ft.month between '2020-04-01' and '2022-03-31';

 select * from dist_veh_type_sales;
 -- ------------------------------------------------------------ TABLE 8 USED IN THE NOTEBOOK-----------------------------------------------------------
create table sect_inv_fy22  as select ft.*, dim_date.fiscal_year_ from fact_ts_ipass as ft inner join dim_date
  where ft.month = dim_date.Date_ and dim_date.fiscal_year_ = '2022';

select * from sect_inv_fy22;

create table inv_sect_fy22 as select round(sum(`investment in cr`),2) as total_inv_cr ,sector  from sect_inv_fy22 
group by sector order by total_inv_cr desc
limit 5;

select * from inv_sect_fy22;
 -- ------------------------------------------------------------ TABLE 9 USED IN THE NOTEBOOK-----------------------------------------------------------

create table dist_inv_fy2019_22 select dim_districts.district, ft.`investment in cr` 
 from fact_ts_ipass as ft join dim_districts on dim_districts.dist_code = ft.dist_code join
 dim_date  where ft.month = dim_date.Date_ and dim_date.fiscal_year_ between '2019' and '2022' ;

create table total_inv_dist_fy19_22 as 
select district, round(sum(`investment in cr`),2) as total_inv_dist 
from dist_inv_fy2019_22 group by district order by sum(`investment in cr`) desc limit 3;

select	* from total_inv_dist_fy19_22;
 -- ------------------------------------------------------------ TABLE 10 USED IN THE NOTEBOOK-----------------------------------------------------------
select dim_districts.district, sum(ft.`investment in cr`) as total_inv, ft.sector 
 from fact_ts_ipass as ft join dim_districts on dim_districts.dist_code = ft.dist_code join
 dim_date  where ft.month = dim_date.Date_ and dim_date.fiscal_year_ between '2019' and '2022' 
 and dim_districts.district = 'Medchal_Malkajgiri'  group by ft.sector order by total_inv desc limit 5;
 
 select dim_districts.district, sum(ft.`investment in cr`) as total_inv , ft.sector 
 from fact_ts_ipass as ft join dim_districts on dim_districts.dist_code = ft.dist_code join
 dim_date  where ft.month = dim_date.Date_ and dim_date.fiscal_year_ between '2019' and '2022' 
 and  dim_districts.district = 'Rangareddy'  group by ft.sector order by total_inv desc limit 5;
 
 select dim_districts.district, sum(ft.`investment in cr`) as total_inv, ft.sector 
 from fact_ts_ipass as ft join dim_districts on dim_districts.dist_code = ft.dist_code join
 dim_date  where ft.month = dim_date.Date_ and dim_date.fiscal_year_ between '2019' and '2022' 
 and dim_districts.district = 'Sangareddy' group by ft.sector order by total_inv desc limit 5;
 -- ------------------------------------------------------------ TABLE 11,12,13 USED IN THE NOTEBOOK-----------------------------------------------------------

create table dist_investments as select dist.district, round(sum(ft.`investment in cr`),2) as total_inv_in_cr 
from fact_ts_ipass as ft inner join dim_districts as dist 
on ft.dist_code = dist.dist_code inner join dim_date as dt on dt.fiscal_year_ between '2021' and '2022'
group by dist.district order by total_inv_in_cr desc ;

create table dist_vehicle_sales as select dist.district, sum(ft.Brand_new_vehicles+ft.`Pre-owned_vehicles`)as total_vehicle_sales 
from fact_transport as ft  join dim_date as dt  join dim_districts as dist
where dist.dist_code = ft.dist_code and  dt.Date_ = ft.month and dt.fiscal_year_ between '2021' and '2022' 
group by dist.district order by total_vehicle_sales desc;

create table dist_stamps_revenue as select d.district, sum(ft.estamps_challans_rev) as total_stamps_revenue from fact_stamps as ft
inner join dim_districts as d inner join dim_date as dt where dt.Date_ = ft.month and d.dist_code = ft.dist_code
and dt.fiscal_year_ between '2021' and '2022' group by d.district order by total_stamps_revenue desc;

select * from dist_investments ;
select * from dist_vehicle_sales ;
select * from dist_stamps_revenue;
 -- ------------------------------------------------------------ TABLE 14,15,16 USED IN THE NOTEBOOK-----------------------------------------------------------
select d.district, ft.sector, round(sum(ft.`investment in cr`),2) as total_inv from fact_ts_ipass as ft 
inner join dim_districts as d where ft.dist_code =  d.dist_code
group by sector, dist_code;

select ft.sector, d.district, round(sum(ft.`investment in cr`),2) as total_inv
from fact_ts_ipass as ft inner join dim_districts as d inner join dim_date as dd
where d.dist_code = ft.dist_code and dd.Date_ = ft.month and dd.fiscal_year_ between '2021' and '2022'
group by ft.sector, d.district order by ft.sector, total_inv desc ;
 -- ------------------------------------------------------------ TABLE 17 USED IN THE NOTEBOOK-----------------------------------------------------------
 select dt.fiscal_year_,dt.quarter_, round(sum(ft.`investment in cr`),2) as total_investment from dim_date as dt 
 inner join fact_ts_ipass as ft
 where dt.Date_ = ft.month  
 group by dt.fiscal_year_,dt.quarter_ order by dt.fiscal_year_ asc ;
 
 select  dt.fiscal_year_, dt.month_, round(sum(ft.`investment in cr`),2) as total_investment from dim_date as dt 
 inner join fact_ts_ipass as ft
 where dt.Date_ = ft.month  
 group by dt.fiscal_year_, dt.month_ order by dt.fiscal_year_ asc ;
  -- ------------------------------------------------------------ TABLE 18, 19 USED IN THE NOTEBOOK-----------------------------------------------------------

select d.district, sum(ft.number_of_employees) as total_emp from fact_ts_ipass
 as ft inner join dim_districts as d where ft.dist_code =d.dist_code
group by d.district order by total_emp desc limit 10;

select d.district, round(sum(ft.`investment in cr`),2) as total_inv_in_cr from fact_ts_ipass
as ft inner join dim_districts as d where ft.dist_code =d.dist_code
group by d.district order by total_inv_in_cr desc limit 10;

select d.district ,sum(ft.Brand_new_vehicles+ft.`Pre-owned_vehicles`) as tot_veh_sales
from fact_transport as ft inner join dim_districts as d
where ft.dist_code = d.dist_code group by d.district order by tot_veh_sales desc limit 10;

select d.district, sum(ft.documents_registered_rev+ft.estamps_challans_rev) as total_rev_gen 
from fact_stamps as ft inner join dim_districts as d where d.dist_code = ft.dist_code
 group by d.district order by total_rev_gen desc limit 10;
   -- ------------------------------------------------------------ TABLE 20,21,22,23 USED IN THE NOTEBOOK-----------------------------------------------------------

select month, vehicleClass_Agriculture from fact_transport ;
 
select month, documents_registered_cnt, estamps_challans_cnt from fact_stamps;

select date(month) as date, number_of_employees from fact_ts_ipass;





